import { Listing } from './types';

const today = new Date().toLocaleDateString('en-US');
const yesterday = new Date(Date.now() - 86400000).toLocaleDateString('en-US');

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'recMOCK001',
    listing_id: '162316605',
    url: 'https://www.immobilienscout24.de/expose/162316605',
    title: 'Gepflegtes Mehrfamilienhaus in Berlin-Spandau',
    address: '13581 Berlin, Spandau',
    postcode: '13581',
    purchase_price: 850000,
    living_area: 420,
    rooms: 18,
    building_type: 'multi_family_house',
    year_built: 1968,
    last_refurbish: '2015',
    energy_class: 'D',
    heating_type: 'central_heating',
    firing_type: 'gas',
    is_rented: 'y',
    days_since_listed: 3,
    price_per_sqm: 2024,
    yield_pct: 7.03,
    yield_rating: '🟢 >5.5%',
    status: 'GO',
    summary: 'Vollvermietetes MFH in Spandau mit stabiler Mieterbasis. Sanierungsstau beim Dach erkennbar, Preis aber eingepreist. Gute Anbindung an öffentliche Verkehrsmittel.',
    risks: '["Sanierungsbedarf Dach","Baujahr 1968"]',
    reason: 'Rendite von 7,03% überschreitet die Mindestanforderung. Alle Dealbreaker-Kriterien erfüllt.',
    analyzed_at: today,
    description: 'MFH mit 6 Einheiten, vollvermietet. Ruhige Lage in Spandau.',
    'Agent Email': 'info@maier-immo.de',
    'Agent Name': 'Maier Immobilien',
    'Agent Phone': '+49 30 123456',
    'Pipeline Stage': 'NEW',
    Notes: '',
    next_action_date: '',
    pre_filter_reason: '',
    flagged_potential_duplicate: false,
  },
  {
    id: 'recMOCK002',
    listing_id: 'immowelt_26TWY6T5DYRF',
    url: 'https://www.immowelt.de/expose/26TWY6T5DYRF',
    title: 'Attraktives Wohn- und Geschäftshaus in Neukölln',
    address: '12043 Berlin, Neukölln',
    postcode: '12043',
    purchase_price: 1250000,
    living_area: 580,
    rooms: 24,
    building_type: 'multi_family_house',
    year_built: 1905,
    last_refurbish: '2019',
    energy_class: 'C',
    heating_type: 'central_heating',
    firing_type: 'gas',
    is_rented: 'y',
    days_since_listed: 7,
    price_per_sqm: 2155,
    yield_pct: 6.25,
    yield_rating: '🟢 >5.5%',
    status: 'GO',
    summary: 'Wohn- und Geschäftshaus mit 8 Einheiten in aufstrebender Lage Neukölln. Gute Mietstruktur mit Gewerbeanteil im EG. Grundrisse optimierungsfähig.',
    risks: '["Altbau vor 1918 – Milieuschutzsatzung prüfen","Gewerbeanteil Leerstandsrisiko"]',
    reason: 'Rendite über 6%, solide Mieterbasis, gute Lage mit Wertsteigerungspotential.',
    analyzed_at: today,
    description: 'Wohn- und Geschäftshaus in zentraler Neuköllner Lage.',
    'Agent Email': '',
    'Agent Name': 'Schmidt & Partner',
    'Agent Phone': '',
    'Pipeline Stage': 'NEW',
    Notes: '',
    next_action_date: '',
    pre_filter_reason: '',
    flagged_potential_duplicate: false,
  },
  {
    id: 'recMOCK003',
    listing_id: '165748439',
    url: 'https://www.immobilienscout24.de/expose/165748439',
    title: 'Mehrfamilienhaus mit Ausbaureserve in Wedding',
    address: '13347 Berlin, Wedding (Mitte)',
    postcode: '13347',
    purchase_price: 980000,
    living_area: 350,
    rooms: 14,
    building_type: 'multi_family_house',
    year_built: 1929,
    last_refurbish: null,
    energy_class: 'E',
    heating_type: 'central_heating',
    firing_type: 'oil',
    is_rented: 'y',
    days_since_listed: 1,
    price_per_sqm: 2800,
    yield_pct: 5.1,
    yield_rating: '🟡 4-5.5%',
    status: 'PRÜFEN',
    summary: 'MFH in Wedding mit Ausbaureserve im DG. Ölheizung muss mittelfristig getauscht werden. IST-Miete leicht unter Markt, Mietsteigerungspotential vorhanden.',
    risks: '["Ölheizung – Austauschpflicht GEG","Energieklasse E","Kein Aufzug"]',
    reason: 'Rendite knapp unter 5,5%, aber Ausbaureserve und Mietsteigerungspotential könnten Gesamtrendite heben.',
    analyzed_at: today,
    description: 'Mehrfamilienhaus mit 5 Einheiten und DG-Ausbaureserve.',
    'Agent Email': 'kontakt@berliner-immo.de',
    'Agent Name': 'Berliner Immobilienkontor',
    'Agent Phone': '+49 30 987654',
    'Pipeline Stage': 'NEW',
    Notes: '',
    next_action_date: '',
    pre_filter_reason: '',
    flagged_potential_duplicate: false,
  },
  {
    id: 'recMOCK004',
    listing_id: 'kleinanzeigen_3297699799',
    url: 'https://www.kleinanzeigen.de/s-anzeige/3297699799',
    title: 'Solides Zinshaus in Reinickendorf',
    address: '13467 Berlin, Hermsdorf (Reinickendorf)',
    postcode: '13467',
    purchase_price: 720000,
    living_area: 310,
    rooms: 12,
    building_type: 'multi_family_house',
    year_built: 1955,
    last_refurbish: '2010',
    energy_class: 'D',
    heating_type: 'central_heating',
    firing_type: 'gas',
    is_rented: 'y',
    days_since_listed: 5,
    price_per_sqm: 2323,
    yield_pct: null,
    yield_rating: '⚪ Unknown',
    status: 'PRÜFEN',
    summary: 'Zinshaus in ruhiger Wohnlage Hermsdorf. IST-Miete nicht angegeben, Renditeberechnung nicht möglich. Grundstück mit Nachverdichtungspotential.',
    risks: '["Unbekannte IST-Miete","Kleinanzeigen – Seriosität prüfen"]',
    reason: 'Keine Renditedaten verfügbar. Lage und Grundstück interessant, IST-Miete muss erfragt werden.',
    analyzed_at: today,
    description: 'Solides Zinshaus mit 4 Wohneinheiten in Hermsdorf.',
    'Agent Email': '',
    'Agent Name': '',
    'Agent Phone': '',
    'Pipeline Stage': 'NEW',
    Notes: '',
    next_action_date: '',
    pre_filter_reason: '',
    flagged_potential_duplicate: false,
  },
  {
    id: 'recMOCK005',
    listing_id: '168234521',
    url: 'https://www.immobilienscout24.de/expose/168234521',
    title: 'Saniertes Altbau-MFH in Charlottenburg',
    address: '10585 Berlin, Charlottenburg',
    postcode: '10585',
    purchase_price: 2100000,
    living_area: 680,
    rooms: 28,
    building_type: 'multi_family_house',
    year_built: 1912,
    last_refurbish: '2022',
    energy_class: 'B',
    heating_type: 'central_heating',
    firing_type: 'gas',
    is_rented: 'y',
    days_since_listed: 2,
    price_per_sqm: 3088,
    yield_pct: 4.2,
    yield_rating: '🟡 4-5.5%',
    status: 'NO-GO',
    summary: 'Kernsaniertes MFH in Top-Lage Charlottenburg. Preis pro m² über 3.000 EUR, Rendite unter 4,5%. Für Value-Add-Strategie ungeeignet.',
    risks: '["Preis/m² > 3.000 EUR","Rendite unter 4,5%","Milieuschutzgebiet"]',
    reason: 'Rendite von 4,2% unterschreitet die Mindestanforderung von 5,5%. Kein Value-Add-Potential nach Kernsanierung.',
    analyzed_at: today,
    description: 'Kernsaniertes Jugendstilhaus mit 10 Wohneinheiten.',
    'Agent Email': 'luxury@berlin-estates.de',
    'Agent Name': 'Berlin Premium Estates',
    'Agent Phone': '+49 30 555000',
    'Pipeline Stage': '',
    Notes: '',
    next_action_date: '',
    pre_filter_reason: '',
    flagged_potential_duplicate: false,
  },
  {
    id: 'recMOCK006',
    listing_id: 'immowelt_89XKRT2PLMN',
    url: 'https://www.immowelt.de/expose/89XKRT2PLMN',
    title: 'Unsaniertes MFH mit Potential in Lichtenberg',
    address: '10365 Berlin, Lichtenberg',
    postcode: '10365',
    purchase_price: 490000,
    living_area: 260,
    rooms: 10,
    building_type: 'multi_family_house',
    year_built: 1958,
    last_refurbish: null,
    energy_class: 'F',
    heating_type: 'stove_heating',
    firing_type: 'not stated',
    is_rented: 'n',
    days_since_listed: 14,
    price_per_sqm: 1885,
    yield_pct: null,
    yield_rating: '⚪ Unknown',
    status: 'NO-GO',
    summary: 'Leerstehend, unsaniert, Einzelofenheizung. Vollständige Kernsanierung erforderlich. Geschätzte Sanierungskosten 400-500k EUR.',
    risks: '["Einzelofenheizung","Leerstand","Vollsanierung nötig","Energieklasse F"]',
    reason: 'Sanierungskosten in Kombination mit Kaufpreis ergeben keine wirtschaftlich darstellbare Rendite.',
    analyzed_at: today,
    description: 'Unsaniertes Mehrfamilienhaus, 4 WE, komplett leerstehend.',
    'Agent Email': '',
    'Agent Name': 'Privat',
    'Agent Phone': '',
    'Pipeline Stage': '',
    Notes: '',
    next_action_date: '',
    pre_filter_reason: '',
    flagged_potential_duplicate: false,
  },
  {
    id: 'recMOCK007',
    listing_id: '170982344',
    url: 'https://www.immobilienscout24.de/expose/170982344',
    title: 'Renditestarkes MFH in Marzahn',
    address: '12685 Berlin, Marzahn',
    postcode: '12685',
    purchase_price: 550000,
    living_area: 380,
    rooms: 16,
    building_type: 'multi_family_house',
    year_built: 1978,
    last_refurbish: '2018',
    energy_class: 'C',
    heating_type: 'central_heating',
    firing_type: 'district_heating',
    is_rented: 'y',
    days_since_listed: 1,
    price_per_sqm: 1447,
    yield_pct: 8.1,
    yield_rating: '🟢 >5.5%',
    status: 'GO',
    summary: 'Attraktives MFH in Marzahn mit 8,1% Brutto-Rendite. Fernwärme, sanierter Zustand. Lage B-Minus, aber starke Cashflow-Perspektive.',
    risks: '["B-Minus Lage","Plattenbauviertel – Image"]',
    reason: 'Hervorragende Rendite von 8,1%, guter Zustand, Fernwärme-Vorteil. Lagerisiko vertretbar bei diesem Preis.',
    analyzed_at: today,
    description: 'MFH mit 8 Einheiten, vollvermietet, Fernwärme.',
    'Agent Email': 'anfrage@ost-immo.de',
    'Agent Name': 'Ost-Berliner Immobilien',
    'Agent Phone': '+49 30 444333',
    'Pipeline Stage': 'CONTACTED',
    Notes: 'Exposé angefordert',
    next_action_date: '',
    pre_filter_reason: '',
    flagged_potential_duplicate: false,
  },
  {
    id: 'recMOCK008',
    listing_id: 'kleinanzeigen_4412789001',
    url: 'https://www.kleinanzeigen.de/s-anzeige/4412789001',
    title: 'ETW-Paket 3 Wohnungen Kreuzberg',
    address: '10999 Berlin, Kreuzberg (Friedrichshain-Kreuzberg)',
    postcode: '10999',
    purchase_price: 680000,
    living_area: 195,
    rooms: 8,
    building_type: 'apartment',
    year_built: 1900,
    last_refurbish: '2016',
    energy_class: 'D',
    heating_type: 'central_heating',
    firing_type: 'gas',
    is_rented: 'y',
    days_since_listed: 10,
    price_per_sqm: 3487,
    yield_pct: 3.8,
    yield_rating: '🔴 <4%',
    status: 'NO-GO',
    summary: 'ETW-Paket in bester Kreuzberger Lage. Preis/m² mit 3.487 EUR sehr hoch. Rendite von nur 3,8% deutlich unter Mindestanforderung.',
    risks: '["Rendite unter 4%","Preis/m² > 3.000","Milieuschutzgebiet","WEG-Struktur"]',
    reason: 'Rendite von 3,8% liegt unter dem Minimum. WEG-Pakete sind zudem komplex in der Verwaltung.',
    analyzed_at: yesterday,
    description: 'Paket aus 3 vermieteten Eigentumswohnungen in Kreuzberg.',
    'Agent Email': '',
    'Agent Name': '',
    'Agent Phone': '',
    'Pipeline Stage': 'PASSED',
    Notes: 'Rendite zu niedrig',
    next_action_date: '',
    pre_filter_reason: '',
    flagged_potential_duplicate: false,
  },
  {
    id: 'recMOCK009',
    listing_id: '171005521',
    url: 'https://www.immobilienscout24.de/expose/171005521',
    title: 'Denkmalgeschütztes MFH Prenzlauer Berg',
    address: '10437 Berlin, Prenzlauer Berg (Pankow)',
    postcode: '10437',
    purchase_price: 1800000,
    living_area: 520,
    rooms: 20,
    building_type: 'multi_family_house',
    year_built: 1898,
    last_refurbish: '2005',
    energy_class: 'E',
    heating_type: 'central_heating',
    firing_type: 'gas',
    is_rented: 'y',
    days_since_listed: 4,
    price_per_sqm: 3462,
    yield_pct: 4.9,
    yield_rating: '🟡 4-5.5%',
    status: 'PRÜFEN',
    summary: 'Denkmalgeschütztes Gründerzeithaus in Prenzlauer Berg. Denkmal-AfA möglich. Rendite grenzwertig, aber steuerliche Vorteile und Top-Lage kompensieren teilweise.',
    risks: '["Denkmalschutzauflagen","Preis/m² > 3.000","Rendite grenzwertig","Milieuschutzgebiet"]',
    reason: 'Rendite an der Untergrenze, aber Denkmal-AfA und Lagepremium könnten die Investition rechtfertigen. Genauere Analyse der steuerlichen Vorteile nötig.',
    analyzed_at: today,
    description: 'Repräsentatives Gründerzeithaus mit Stuckfassade.',
    'Agent Email': 'berlin@premium-wohnen.de',
    'Agent Name': 'Premium Wohnen Berlin',
    'Agent Phone': '+49 30 777888',
    'Pipeline Stage': 'NEW',
    Notes: '',
    next_action_date: '',
    pre_filter_reason: '',
    flagged_potential_duplicate: true,
  },
  {
    id: 'recMOCK010',
    listing_id: 'immowelt_55MNRT7QWXZ',
    url: 'https://www.immowelt.de/expose/55MNRT7QWXZ',
    title: 'Kleines MFH in Tempelhof – Kapitalanlage',
    address: '12103 Berlin, Tempelhof',
    postcode: '12103',
    purchase_price: 620000,
    living_area: 280,
    rooms: 12,
    building_type: 'multi_family_house',
    year_built: 1960,
    last_refurbish: '2014',
    energy_class: 'D',
    heating_type: 'central_heating',
    firing_type: 'gas',
    is_rented: 'y',
    days_since_listed: 6,
    price_per_sqm: 2214,
    yield_pct: 5.8,
    yield_rating: '🟢 >5.5%',
    status: 'GO',
    summary: 'Kleines aber feines MFH in Tempelhof. Gute Verkehrsanbindung, alle Wohnungen vermietet. Moderate Sanierungskosten zu erwarten.',
    risks: '["Baujahr 1960 – Leitungen prüfen","Kleine Grundrisse"]',
    reason: 'Rendite von 5,8% über der Mindestanforderung. Überschaubares Investitionsvolumen mit guter Lage.',
    analyzed_at: today,
    description: 'MFH mit 4 Wohneinheiten, voll vermietet seit 2018.',
    'Agent Email': 'info@tempelhof-immo.de',
    'Agent Name': 'Tempelhof Immobilien',
    'Agent Phone': '+49 30 666777',
    'Pipeline Stage': 'VIEWING',
    Notes: 'Besichtigung am Freitag 14:00',
    next_action_date: '2026-03-07',
    pre_filter_reason: '',
    flagged_potential_duplicate: false,
  },
];
